// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAx8ZSVaiV42SGoaPpdHgOfOa8Iaks9_Q',
    appId: '1:666088846137:web:8bbdb4aa012a4810bdeee8',
    messagingSenderId: '666088846137',
    projectId: 'proyek-uas-pakfuad',
    authDomain: 'proyek-uas-pakfuad.firebaseapp.com',
    storageBucket: 'proyek-uas-pakfuad.firebasestorage.app',
    measurementId: 'G-VXYRKYKP3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7SWIuWqvh_IdLoFKnvC5nGQ1u0k0naBQ',
    appId: '1:666088846137:android:682927003ef1f1b4bdeee8',
    messagingSenderId: '666088846137',
    projectId: 'proyek-uas-pakfuad',
    storageBucket: 'proyek-uas-pakfuad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7-GJE7IDQseTdKrJQxrMcHU_-jt3wx9I',
    appId: '1:666088846137:ios:01b55a55a1cedd28bdeee8',
    messagingSenderId: '666088846137',
    projectId: 'proyek-uas-pakfuad',
    storageBucket: 'proyek-uas-pakfuad.firebasestorage.app',
    iosClientId: '666088846137-od24jhvmkpl50a5raojh2620c9um9tqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyekUasPakfuad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7-GJE7IDQseTdKrJQxrMcHU_-jt3wx9I',
    appId: '1:666088846137:ios:01b55a55a1cedd28bdeee8',
    messagingSenderId: '666088846137',
    projectId: 'proyek-uas-pakfuad',
    storageBucket: 'proyek-uas-pakfuad.firebasestorage.app',
    iosClientId: '666088846137-od24jhvmkpl50a5raojh2620c9um9tqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyekUasPakfuad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAx8ZSVaiV42SGoaPpdHgOfOa8Iaks9_Q',
    appId: '1:666088846137:web:dc0f977f936ca270bdeee8',
    messagingSenderId: '666088846137',
    projectId: 'proyek-uas-pakfuad',
    authDomain: 'proyek-uas-pakfuad.firebaseapp.com',
    storageBucket: 'proyek-uas-pakfuad.firebasestorage.app',
    measurementId: 'G-6V1FNTJ0NP',
  );
}
